___ACCIONES COLOMBIA___

In [110]:
#Cargar Librerías
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import os
import re
import openpyxl
from market_col.dir_set import project_root_nb
from market_col.figures import static_plot
from market_col.figures import html_2_plot
from market_col.plotly import plotly_oneplot
from market_col.company_table import company_table

In [111]:
#Ajustamos el directorio de trabajo al directorio raíz del proyecto
PROJECT_DIR = Path(project_root_nb())

In [112]:
# Ejecutamos el script para actualizar los datos de acciones
#import subprocess
#import sys

#subprocess.run([sys.executable, "Scripts/Col-stocks.py"])

In [113]:
# Leemos datos de acciones de Colombia desde un archivo CSV
# Definimos la variable de Fecha en formato de fecha
data = pd.read_csv(f"{PROJECT_DIR}/Data/Colombia_Stocks/Acciones_colab.csv")
data['Fecha'] = pd.to_datetime(data['Fecha'])

In [114]:
Cemargos = data[data["Nemotécnico"] == "CEMARGOS"]
PFCemargos = data[data["Nemotécnico"] == "PFCEMARGOS"]
Grupoargos = data[data["Nemotécnico"] == "GRUPOARGOS"]
Cibest = data[data["Nemotécnico"] == "CIBEST"]
Ecopetrol = data[data["Nemotécnico"] == "ECOPETROL"]
GrupoAval = data[data["Nemotécnico"] == "GRUPOAVAL"]
Isa = data[data["Nemotécnico"] == "ISA"]
PFaval = data[data["Nemotécnico"] == "PFAVAL"]
PFDavigroup = data[data["Nemotécnico"] == "PFDAVIGRP"]
COLCAP = data[data["Nemotécnico"] == "ICOLCAP"]

In [115]:
datainput = pd.read_excel(f"{PROJECT_DIR}/Data/colombia_company_data/table_Input.xlsx", index_col= 0)

In [ ]:
#static_plot(COLCAP, "black")
plotly_oneplot(COLCAP, x_col="Fecha", y_col="Precios (último /cierre)", plot_title=f"COLCAP - Last Price {COLCAP["Precios (último /cierre)"].iloc[-1]:,.2f}",
                color_in="black", date_marker = pd.to_datetime("2026-07-14"))

#grafico_html = HTMLcemargos.to_html(full_html=False, include_plotlyjs="cdn")
#input_table = company_table(datainput, "CEMARGOS")
#tabla_html = input_table.to_html()
#graficoprueba = html_2_plot(grafico_html, tabla_html)

In [147]:
def plot2(accion, nemo, color):
    HTMLcemargos = plotly_oneplot(accion, x_col="Fecha", y_col="Precios (último /cierre)", plot_title=f"{nemo} - Last Price: {accion["Precios (último /cierre)"].iloc[-1]:,.2f}", 
                                  color_in=color, date_marker = pd.to_datetime("2026-07-14"))
    grafico_html = HTMLcemargos.to_html(full_html=False, include_plotlyjs="cdn")
    input_table = company_table(datainput, nemo)
    tabla_html = input_table.to_html()
    graficoprueba = html_2_plot(grafico_html, tabla_html)

In [148]:
#static_plot(Cemargos, "green")
#plotly_oneplot(PFCemargos, "Fecha", "Precios (último /cierre)", plot_title="PF Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
plot2(Cemargos, "CEMARGOS", "green")

In [119]:
"""#static_plot(Cemargos, "green")
graf = plotly_oneplot(Cemargos, "Fecha", "Precios (último /cierre)", plot_title="Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
graf.write_html("grafico.html",
                    config={"responsive": True})"""

'#static_plot(Cemargos, "green")\ngraf = plotly_oneplot(Cemargos, "Fecha", "Precios (último /cierre)", plot_title="Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))\ngraf.write_html("grafico.html",\n                    config={"responsive": True})'

In [120]:
#static_plot(Cemargos, "green")
#plotly_oneplot(PFCemargos, "Fecha", "Precios (último /cierre)", plot_title="PF Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
plot2(PFCemargos, "PFCEMARGOS", "green")

In [121]:
#static_plot(Cemargos, "green")
#plotly_oneplot(Grupoargos, "Fecha", "Precios (último /cierre)", plot_title="Grupo Argos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
plot2(Grupoargos, "GRUPOARGOS", "green")

In [122]:
#static_plot(Cibest, "blue")
#plotly_oneplot(Cibest, "Fecha", "Precios (último /cierre)", plot_title="Cibest", color_in="blue", date_marker = pd.to_datetime("2026-07-14"))
plot2(Cibest, "CIBEST", "blue")

In [123]:
#static_plot(Ecopetrol, "green")
plotly_oneplot(Ecopetrol, "Fecha", "Precios (último /cierre)", "Ecopetrol", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
plot2(Ecopetrol, "ECOPETROL", "green")

In [124]:
#static_plot(GrupoAval, "blue")
#plotly_oneplot(GrupoAval, "Fecha", "Precios (último /cierre)", "GrupoAval", color_in="blue", date_marker = pd.to_datetime("2026-07-14"))
plot2(GrupoAval, "GRUPOAVAL", "blue")

In [125]:
#static_plot(PFaval, "darkblue")
#plotly_oneplot(PFaval, "Fecha", "Precios (último /cierre)", "PFaval", color_in="darkblue", date_marker = pd.to_datetime("2026-07-14"))
plot2(PFaval, "PFAVAL", "darkblue")

In [126]:
#static_plot(Isa, "orange")
#plotly_oneplot(Isa, "Fecha", "Precios (último /cierre)", "Isa", color_in="orange", date_marker = pd.to_datetime("2026-07-14"))
plot2(Isa, "ISA", "orange")

In [127]:
#static_plot(PFDavigroup, "pink")
plotly_oneplot(PFDavigroup, "Fecha", "Precios (último /cierre)", "PFDavigroup", color_in="pink", date_marker = pd.to_datetime("2026-07-14"))
plot2(PFDavigroup, "PFDAVIGRP", "pink")

In [128]:
TRM = pd.read_csv(f"{PROJECT_DIR}/Data/TRM/newTRM.csv")
TRM["fecha"] = pd.to_datetime(TRM["fecha"])
TRM.tail(3)

          fecha    valor
1570 2026-08-17  3128.65
1571 2026-08-18  3128.65
1572 2026-08-19  3098.79

In [129]:
plotly_oneplot(TRM[TRM["fecha"]>="2025-05-01"], "fecha", "valor", "TRM", color_in="black", date_marker = pd.to_datetime("2026-07-14"))