___ACCIONES COLOMBIA___

In [25]:
#Cargar Librerías
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import os
import re
import openpyxl
from market_col.dir_set import project_root_nb
from market_col.figures import static_plot
from market_col.figures import html_2_plot
from market_col.plotly import plotly_oneplot
from market_col.company_table import company_table

In [2]:
#Ajustamos el directorio de trabajo al directorio raíz del proyecto
PROJECT_DIR = Path(project_root_nb())

In [3]:
# Ejecutamos el script para actualizar los datos de acciones
#import subprocess
#import sys

#subprocess.run([sys.executable, "Scripts/Col-stocks.py"])

In [4]:
# Leemos datos de acciones de Colombia desde un archivo CSV
# Definimos la variable de Fecha en formato de fecha
data = pd.read_csv(f"{PROJECT_DIR}/Data/Colombia_Stocks/Acciones_colab.csv")
data['Fecha'] = pd.to_datetime(data['Fecha'])

In [5]:
Cemargos = data[data["Nemotécnico"] == "CEMARGOS"]
PFCemargos = data[data["Nemotécnico"] == "PFCEMARGOS"]
Grupoargos = data[data["Nemotécnico"] == "GRUPOARGOS"]
Cibest = data[data["Nemotécnico"] == "CIBEST"]
Ecopetrol = data[data["Nemotécnico"] == "ECOPETROL"]
GrupoAval = data[data["Nemotécnico"] == "GRUPOAVAL"]
Isa = data[data["Nemotécnico"] == "ISA"]
PFaval = data[data["Nemotécnico"] == "PFAVAL"]
PFDavigroup = data[data["Nemotécnico"] == "PFDAVIGRP"]
COLCAP = data[data["Nemotécnico"] == "ICOLCAP"]

In [ ]:
datainput = pd.read_excel(f"{PROJECT_DIR}/Data/colombia_company_data/table_Input.xlsx", index_col= 0)

In [28]:
#static_plot(COLCAP, "black")
HTMLcemargos = plotly_oneplot(Cemargos, x_col="Fecha", y_col="Precios (último /cierre)", plot_title="CEMARGOS", color_in="green", date_marker = pd.to_datetime("2026-07-14"))
grafico_html = HTMLcemargos.to_html(full_html=False, include_plotlyjs="cdn")
input_table = company_table(datainput, "CEMARGOS")
tabla_html = input_table.to_html()
html_2_plot(grafico_html, tabla_html)

In [10]:
html = f"""
<div style="
    display: flex;
    align-items: flex-start;
    gap: 30px;
">

    <div style="flex: 1;">
        {grafico_html}
    </div>

    <div style="
        width: 400px;
        overflow-x: auto;
    ">
        {tabla_html}
    </div>

</div>
"""

display(HTML(html))

In [11]:
#static_plot(Cemargos, "green")
plotly_oneplot(Cemargos, "Fecha", "Precios (último /cierre)", plot_title="Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))

In [12]:
#static_plot(Cemargos, "green")
plotly_oneplot(PFCemargos, "Fecha", "Precios (último /cierre)", plot_title="PF Cemargos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))

In [13]:
#static_plot(Cemargos, "green")
plotly_oneplot(Grupoargos, "Fecha", "Precios (último /cierre)", plot_title="Grupo Argos", color_in="green", date_marker = pd.to_datetime("2026-07-14"))

In [14]:
#static_plot(Cibest, "blue")
plotly_oneplot(Cibest, "Fecha", "Precios (último /cierre)", plot_title="Cibest", color_in="blue", date_marker = pd.to_datetime("2026-07-14"))

In [15]:
#static_plot(Ecopetrol, "green")
plotly_oneplot(Ecopetrol, "Fecha", "Precios (último /cierre)", "Ecopetrol", color_in="green", date_marker = pd.to_datetime("2026-07-14"))

In [16]:
#static_plot(GrupoAval, "blue")
plotly_oneplot(GrupoAval, "Fecha", "Precios (último /cierre)", "GrupoAval", color_in="blue", date_marker = pd.to_datetime("2026-07-14"))

In [17]:
#static_plot(PFaval, "darkblue")
plotly_oneplot(PFaval, "Fecha", "Precios (último /cierre)", "PFaval", color_in="darkblue", date_marker = pd.to_datetime("2026-07-14"))

In [18]:
#static_plot(Isa, "orange")
plotly_oneplot(Isa, "Fecha", "Precios (último /cierre)", "Isa", color_in="orange", date_marker = pd.to_datetime("2026-07-14"))

In [19]:
#static_plot(PFDavigroup, "pink")
plotly_oneplot(PFDavigroup, "Fecha", "Precios (último /cierre)", "PFDavigroup", color_in="pink", date_marker = pd.to_datetime("2026-07-14"))

In [20]:
TRM = pd.read_csv(f"{PROJECT_DIR}/Data/TRM/newTRM.csv")
TRM["fecha"] = pd.to_datetime(TRM["fecha"])
TRM.tail(3)

          fecha    valor
1565 2026-08-12  3121.07
1566 2026-08-13  3123.28
1567 2026-08-14  3127.51

In [21]:
plotly_oneplot(TRM[TRM["fecha"]>="2025-07-01"], "fecha", "valor", "TRM", color_in="black", date_marker = pd.to_datetime("2026-07-14"))